trigger:
- master


pool:
  name: 'Default'

steps:
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1 (7a79750b-132f-494e-858d-b290a4586855)'  # Replace with the correct service connection name
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--output $(Build.BinariesDirectory)/publish_output --configuration Release'  # Fixed typo in 'configuration'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/publish_output'  # Corrected path to the output folder
    includeRootFolder: false  # You typically don't want to include the root folder itself in the archive
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path to where the artifacts were archived
    ArtifactName: 'drop'  # Artifact name
    publishLocation: 'Container'  # Publish the artifact to the Azure DevOps artifact container
